import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
        './resources/js/**/*.js',
    ],

    theme: {
        extend: {
            colors: {
                "on-primary": "#003739",
                "surface-container-low": "#131b2e",
                "surface-bright": "#31394d",
                "warning-amber": "#F59E0B",
                "obsidian-surface": "#0F172A",
                "secondary-fixed": "#62fae3",
                "on-tertiary": "#490080",
                "error-rose": "#F43F5E",
                "surface-tint": "#00dce5",
                "outline-variant": "#3a494a",
                "on-surface-variant": "#b9caca",
                "tertiary-container": "#edd4ff",
                "surface-container": "#171f33",
                "on-tertiary-fixed-variant": "#6900b3",
                "ai-purple": "#A855F7",
                "on-tertiary-fixed": "#2c0051",
                "primary-fixed-dim": "#00dce5",
                "surface-container-highest": "#2d3449",
                "on-secondary-container": "#004d44",
                "error": "#ffb4ab",
                "inverse-primary": "#00696e",
                "error-container": "#93000a",
                "on-tertiary-container": "#872fd5",
                "obsidian-base": "#020617",
                "on-secondary": "#003731",
                "secondary-fixed-dim": "#3cddc7",
                "on-secondary-fixed": "#00201c",
                "on-background": "#dae2fd",
                "outline": "#849495",
                "surface-container-lowest": "#060e20",
                "info-cyan": "#06B6D4",
                "on-error-container": "#ffdad6",
                "tertiary": "#fff8fd",
                "surface-variant": "#2d3449",
                "tertiary-fixed-dim": "#ddb7ff",
                "primary-fixed": "#63f7ff",
                "success-emerald": "#10B981",
                "on-surface": "#dae2fd",
                "background": "#0b1326",
                "secondary-container": "#03c6b2",
                "surface": "#0b1326",
                "surface-dim": "#0b1326",
                "obsidian-elevated": "#1E293B",
                "on-error": "#690005",
                "secondary": "#44e2cd",
                "primary": "#e9feff",
                "on-primary-fixed": "#002021",
                "surface-container-high": "#222a3d",
                "tertiary-fixed": "#f0dbff",
                "on-secondary-fixed-variant": "#005047",
                "on-primary-fixed-variant": "#004f53",
                "primary-container": "#00f5ff",
                "inverse-on-surface": "#283044",
                "on-primary-container": "#006c71",
                "inverse-surface": "#dae2fd"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "gutter": "24px",
                "margin-desktop": "64px",
                "margin-mobile": "16px",
                "base": "4px",
                "container-max": "1440px"
            },
            fontFamily: {
                "label-sm": ["JetBrains Mono", ...defaultTheme.fontFamily.sans],
                "label-md": ["JetBrains Mono", ...defaultTheme.fontFamily.sans],
                "headline-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "headline-lg-mobile": ["Inter", ...defaultTheme.fontFamily.sans],
                "body-md": ["Inter", ...defaultTheme.fontFamily.sans],
                "body-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "display-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "body-sm": ["Inter", ...defaultTheme.fontFamily.sans],
                "headline-md": ["Inter", ...defaultTheme.fontFamily.sans],
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                "label-sm": ["12px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
            },
            transitionProperty: {
                'width': 'width',
                'spacing': 'margin, padding',
            }
        },
    },

    plugins: [forms],
};
